const requiredFieldsForAI = [
  "id_perawat",
  "id_ruangan",
  "nama_pasien",
  "no_rm",
  "umur",
  "jenis_kelamin",
  "tgl_msk_rs",
  "unit_yang_melaporkan",
  "lokasi_insiden",
  "tgl_insiden",
  "judul_insiden",
  "kronologi",
  "tindakan_awal",
  "tindakan_oleh",
  "dampak",
  "probabilitas",
];

const requiredFieldsForConfirmation = [
  "id_perawat",
  "id_ruangan",
  "nama_pasien",
  "no_rm",
  "umur",
  "jenis_kelamin",
  "tgl_msk_rs",
  "unit_yang_melaporkan",
  "lokasi_insiden",
  "tgl_insiden",
  "judul_insiden",
  "kronologi",
  "tindakan_awal",
  "tindakan_oleh",
  "dampak",
  "probabilitas",
  "kategori", 
  "rekomendasi_tindakan",
];

module.exports = { requiredFieldsForConfirmation, requiredFieldsForAI };